name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    name: Run tests with pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev,tests]"
      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install libsndfile1
      - name: Preparation of pytest
        run: |
          python tests/scripts/download_all.py
      - name: Pytest (run all tests including redundant ones)
        id: run_redundant
        if: startsWith(github.head_ref, 'release/')
        run: |
          pytest --run-redundant -vvv -n 16 --cov=./ssspy --cov-report=xml tests/ssspy/
      - name: Pytest (skip redundant tests)
        if: steps.run_redundant.conclusion == 'skipped'
        run: |
          pytest -vvv -n 16 --cov=./ssspy --cov-report=xml tests/ssspy/
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
